baseURL = "https://modoeconomista.github.io/meu-blog/"
title = "Meu Blog"
theme = "PaperMod"
languageCode = "pt-br"
defaultContentLanguage = "pt"
[pagination]
  pagerSize = 10


[params]
  author = "Bruno Castro"
  description = "Blog sobre economia"
  keywords = ["estatística", "educação", "jogos digitais", "hugo"]
  env = "production"

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostTags = true
  ShowPostCategories = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false

  defaultTheme = "auto"
  disableThemeToggle = false


   [params.logo]
  image = "images/logo.png"
  alt = "Logo do Blog"


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/modoeconomista"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/SEU_USUARIO"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:email@email.com"

[params.footer]
  copyright = "© 2025 - Meu Blog"
  poweredby = false

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Sobre"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Categorias"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5

[params.assets]
  customCSS = ["css/custom.css"]
