baseURL = "https://modoeconomista.github.io/"
languageCode = "pt-br"
title = "Meu Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
